project:
  name: test_java_hexagonal_rest_jpa_micronaut

micronaut:
  server:
    port: 8080
  application:
    name: ${project.name}

datasources:
  default:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./db/localdb;AUTO_SERVER=TRUE;DB_CLOSE_ON_EXIT=TRUE
    username: sa
    password: ''

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
